name: "💡 Feature Request"
description: Create a new ticket for a new feature request
title: "💡 [REQUEST] - <title>"
labels: [
  "feature"
]
assignees: 
  - SampleAssignee
body:
  - type: input
    id: start_date
    attributes:
      label: "Start Date"
      description: Start of development
      placeholder: "YYYY-MM-DD"
    validations:
      required: false  
  - type: input
    id: target_date
    attributes:
      label: "Target Date"
      description: Target completion date for development
      placeholder: "YYYY-MM-DD"
    validations:
      required: false  
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      value: |
          ```[tasklist]
          ## (What do engineers have to do step by step?)
          - [ ] Verify the issue
          - [ ] Solve the issue
          - [ ] Test the solution
          ```