name: Extract and Update Project Fields
on:
  issues:
    types: [opened, edited]

jobs:
  extract-and-update:
    runs-on: ubuntu-latest
    steps:
      - name : Extract Issue Fields
        id : extract 
        uses: stefanbuck/github-issue-parser@v3
      - name: Add to project
        id: add
        uses: actions/add-to-project@v0.5.0 
        with:
          project-url: ${{ vars.PROJECT_URL}}
          github-token: ${{ secrets.PROJECTS_TOKEN }}
      - name : Update Project Item with Issue Fields
        id : update 
        uses: EndBug/project-fields@v2
        with:
          operation: set
          fields: Priority, Size, Estimate, Start Date, Target Date
          project_url: ${{ vars.PROJECT_URL}}
          github_token: ${{ secrets.PROJECTS_TOKEN }}
          values: ${{ steps.extract.outputs.issueparser_priority }}, ${{ steps.extract.outputs.issueparser_size }}, ${{ steps.extract.outputs.issueparser_estimate }}, ${{ steps.extract.outputs.issueparser_start_date }}, ${{ steps.extract.outputs.issueparser_end_date }}